export const STORAGE_KEYS = {
  USER_PROFILE: "USER_PROFILE",
  PROFILE_COMPLETED: 'PROFILE_COMPLETED',

  SETUP_BASIC_DONE: "SETUP_BASIC_DONE",
  SETUP_GOALS_DONE: "SETUP_GOALS_DONE",
  SETUP_WORKOUT_DONE: "SETUP_WORKOUT_DONE",

  USER_NAME: "USER_NAME",
  BF_WEIGHT_KG: "BF_WEIGHT_KG",
  WATER_DATA: "WATER_DATA",

  CALORIES_DATA: "CALORIES_DATA_V2",
};